import { StyleSheet } from 'react-native';
import { COLORS } from '../../../shared/styles/colors.styles';
import { FONT_SIZES, FONT_WEIGHT, SPACING } from '../../../shared/styles/spacing.styles';

const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
  modalCard: {
    width: '92%',
    maxWidth: 880,
    backgroundColor: '#1e1f22',
    borderColor: '#4a4d52',
    borderWidth: 1,
    borderRadius: 10,
    padding: SPACING.MEDIUM,
    gap: SPACING.SMALL,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerActions: {
    flexDirection: 'row',
    gap: SPACING.SMALL,
  },
  titleInput: {
    color: COLORS.WHITE,
    fontSize: FONT_SIZES.LARGE,
    fontWeight: FONT_WEIGHT.MEDIUM,
    borderBottomWidth: 0,
  },
  descriptionInput: {
    color: COLORS.OFF_WHITE,
    fontSize: FONT_SIZES.MEDIUM,
    borderBottomWidth: 0,
  },
  chipsRow: {
    flexDirection: 'row',
    gap: SPACING.SMALL,
    paddingVertical: SPACING.EXTRA_SMALL,
  },
  chipsAnchor: {
    position: 'relative',
    zIndex: 40,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.EXTRA_SMALL,
    borderWidth: 1,
    borderColor: '#44474d',
    borderRadius: SPACING.SMALL,
    paddingHorizontal: SPACING.SMALL,
    paddingVertical: SPACING.SMALL,
    backgroundColor: '#23252a',
  },
  chipText: {
    color: COLORS.OFF_WHITE,
    fontSize: FONT_SIZES.SMALL,
  },
  reminderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reminderLabel: {
    color: COLORS.OFF_WHITE,
    fontSize: FONT_SIZES.SMALL,
  },
  reminderSummary: {
    color: COLORS.WHITE,
    fontSize: FONT_SIZES.SMALL,
  },
  panelContainer: {
    backgroundColor: '#25272d',
    borderWidth: 0,
    borderRadius: SPACING.SMALL,
    position: 'absolute',
  },
  datePickerContainer: {
    position: 'absolute',
    top: '100%',
    left: 0,
    marginTop: SPACING.EXTRA_SMALL,
    width: 340,
    backgroundColor: '#25272d',
    borderWidth: 1,
    borderColor: '#3f4248',
    borderRadius: SPACING.SMALL,
    padding: SPACING.SMALL,
    gap: SPACING.SMALL,
    zIndex: 60,
    elevation: 24,
  },
  dateQuickList: {
    gap: SPACING.SMALL,
  },
  dateQuickRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SMALL,
  },
  dateQuickText: {
    color: COLORS.WHITE,
    fontSize: FONT_SIZES.MEDIUM,
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  calendarMonthText: {
    color: COLORS.WHITE,
    fontSize: FONT_SIZES.MEDIUM,
    fontWeight: FONT_WEIGHT.BOLD,
  },
  calendarHeaderActions: {
    flexDirection: 'row',
    gap: SPACING.SMALL,
  },
  calendarWeekdays: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  calendarWeekdayText: {
    width: '14.2%',
    textAlign: 'center',
    color: COLORS.OFF_WHITE,
    fontSize: FONT_SIZES.SMALL,
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calendarCell: {
    width: '14.2%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SPACING.SMALL,
    borderRadius: 999,
  },
  calendarCellSelected: {
    backgroundColor: COLORS.RED_DEEP,
  },
  calendarCellText: {
    color: COLORS.WHITE,
    fontSize: FONT_SIZES.SMALL,
  },
  calendarCellTextSelected: {
    color: COLORS.RED_TOMATO,
    fontWeight: FONT_WEIGHT.BOLD,
  },
  manualDateInput: {
    borderWidth: 1,
    borderColor: '#44474d',
    borderRadius: SPACING.SMALL,
    color: COLORS.WHITE,
    paddingHorizontal: SPACING.SMALL,
    paddingVertical: SPACING.SMALL,
  },
  dateActionButton: {
    borderWidth: 1,
    borderColor: '#44474d',
    borderRadius: SPACING.SMALL,
    paddingHorizontal: SPACING.SMALL,
    paddingVertical: SPACING.SMALL,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.EXTRA_SMALL,
  },
  dateActionButtonText: {
    color: COLORS.OFF_WHITE,
    fontSize: FONT_SIZES.SMALL,
  },
  repeatPanel: {
    borderWidth: 1,
    borderColor: '#44474d',
    borderRadius: SPACING.SMALL,
    backgroundColor: '#2a2d32',
  },
  repeatPanelOption: {
    paddingHorizontal: SPACING.MEDIUM,
    paddingVertical: SPACING.SMALL,
  },
  repeatPanelOptionText: {
    color: COLORS.WHITE,
    fontSize: FONT_SIZES.MEDIUM,
  },
  timePanel: {
    borderWidth: 1,
    borderColor: '#44474d',
    borderRadius: SPACING.SMALL,
    backgroundColor: '#2a2d32',
    padding: SPACING.SMALL,
    gap: SPACING.SMALL,
  },
  timePanelFieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SMALL,
  },
  timePanelFieldLabel: {
    width: 80,
    color: COLORS.WHITE,
    fontSize: FONT_SIZES.SMALL,
  },
  timePanelInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#55585f',
    borderRadius: SPACING.SMALL,
    color: COLORS.WHITE,
    paddingHorizontal: SPACING.SMALL,
    paddingVertical: SPACING.SMALL,
  },
  timePanelButtons: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: SPACING.SMALL,
  },
  repeatSummaryText: {
    color: COLORS.OFF_WHITE,
    fontSize: FONT_SIZES.SMALL,
  },
  bottomRow: {
    borderTopWidth: 1,
    borderTopColor: '#3f4248',
    paddingTop: SPACING.SMALL,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'relative',
  },
  bottomLeftRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SMALL,
  },
  breadcrumbHash: {
    color: '#5ca2ff',
    fontSize: FONT_SIZES.SMALL,
  },
  breadcrumbText: {
    color: COLORS.WHITE,
    fontSize: FONT_SIZES.SMALL,
  },
  breadcrumbDivider: {
    color: COLORS.OFF_WHITE,
  },
  projectSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.EXTRA_SMALL,
  },
  projectSelectorAnchor: {
    position: 'relative',
    zIndex: 35,
  },
  projectSelectorText: {
    color: COLORS.OFF_WHITE,
    fontSize: FONT_SIZES.MEDIUM,
    fontWeight: FONT_WEIGHT.BOLD,
  },
  projectDropdown: {
    position: 'absolute',
    left: 0,
    top: '100%',
    marginTop: SPACING.EXTRA_SMALL,
    width: 220,
    backgroundColor: '#25272d',
    borderWidth: 1,
    borderColor: '#44474d',
    borderRadius: SPACING.SMALL,
    zIndex: 30,
    elevation: 20,
  },
  projectDropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: SPACING.SMALL,
    paddingHorizontal: SPACING.MEDIUM,
    paddingVertical: SPACING.SMALL,
  },
  projectDropdownItemSelected: {
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  projectDropdownItemText: {
    color: COLORS.WHITE,
    fontSize: FONT_SIZES.SMALL,
    flex: 1,
  },
  bottomActions: {
    flexDirection: 'row',
    gap: SPACING.SMALL,
  },
  actionButton: {
    paddingHorizontal: SPACING.MEDIUM,
    paddingVertical: SPACING.SMALL,
    borderRadius: SPACING.SMALL,
    minWidth: 92,
    alignItems: 'center',
  },
  actionButtonMuted: {
    backgroundColor: '#474a51',
  },
  actionButtonMutedText: {
    color: COLORS.WHITE,
    fontSize: FONT_SIZES.MEDIUM,
    fontWeight: FONT_WEIGHT.MEDIUM,
  },
  actionButtonPrimary: {
    backgroundColor: '#5a2d2d',
  },
  actionButtonPrimaryText: {
    color: '#b9b9b9',
    fontSize: FONT_SIZES.MEDIUM,
    fontWeight: FONT_WEIGHT.BOLD,
  },
  reminderModalCard: {
    width: '90%',
    maxWidth: 420,
    backgroundColor: '#25272d',
    borderRadius: SPACING.MEDIUM,
    borderWidth: 1,
    borderColor: '#44474d',
    padding: SPACING.MEDIUM,
    gap: SPACING.SMALL,
  },
  reminderTitle: {
    color: COLORS.WHITE,
    fontSize: FONT_SIZES.LARGE,
    fontWeight: FONT_WEIGHT.BOLD,
  },
  reminderTabs: {
    flexDirection: 'row',
    backgroundColor: '#30333a',
    borderRadius: 999,
    padding: 2,
  },
  reminderTab: {
    flex: 1,
    paddingVertical: SPACING.SMALL,
    alignItems: 'center',
    borderRadius: 999,
  },
  reminderTabActive: {
    backgroundColor: '#1d1f23',
  },
  reminderTabText: {
    color: COLORS.WHITE,
    fontSize: FONT_SIZES.SMALL,
    fontWeight: FONT_WEIGHT.MEDIUM,
  },
  reminderTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SMALL,
    borderWidth: 1,
    borderColor: '#44474d',
    borderRadius: SPACING.SMALL,
    paddingHorizontal: SPACING.SMALL,
    paddingVertical: SPACING.SMALL,
  },
  reminderTimeInput: {
    flex: 1,
    color: COLORS.WHITE,
    fontSize: FONT_SIZES.MEDIUM,
  },
  reminderAvatar: {
    width: 20,
    height: 20,
    borderRadius: 10,
    overflow: 'hidden',
    textAlign: 'center',
    textAlignVertical: 'center',
    backgroundColor: COLORS.RED_DEEP,
    color: COLORS.WHITE,
    fontSize: FONT_SIZES.EXTRA_SMALL,
  },
  reminderHintText: {
    color: COLORS.OFF_WHITE,
    fontSize: FONT_SIZES.SMALL,
    lineHeight: 20,
  },
  reminderActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: SPACING.SMALL,
  },
});

export default styles;
